spring.application.name=KilimoSmart

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/KilimoSmart
spring.datasource.username=root
spring.datasource.password=Khalil@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Weather API
weather.api.key=1af0e13533759d64610445e4de5e26ae
weather.api.url=http://api.openweathermap.org/data/2.5/weather

springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=UlrdEEQi12Kmh8yHw7bHk2hG9RCE4/T6hIwA3xo5Sviitc3XIMoBnFC98qfOG/cGmKbkKISxvpvcj+leuZQWCg==
jwt.expiration=86400000

# Default Super Admin Account (Bootstrap Admin)
app.admin.username=superadmin
app.admin.email=superadmin@gmail.com
app.admin.password=Admin123
